name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'destroy' to confirm you want to run this workflow"
        required: true
        default: ""

jobs:
  destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest
    environment: aws

    # Define environment variables at the job level
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: trading-app/back-end

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 1: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 2: Initialize Terraform
      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      # Step 3: Destroy Terraform resources
      - name: Destroy Terraform resources
        env:
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_github_repo: ${{ github.repository }}
          TF_VAR_github_ref: ${{ github.ref_name }}
          TF_VAR_ecr_repo: ${{ env.ECR_REPOSITORY }}
          TF_VAR_ecr_reg: ${{ steps.login-ecr.outputs.registry }}
          TF_VAR_image_tag: ${{ github.sha }}
        run: |
          cd terraform
          terraform destroy -auto-approve
